"""Agregando direccion a perfil

Revision ID: 946569124d0d
Revises: 9c05c2079084
Create Date: 2026-02-17 15:56:32.641497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '946569124d0d'
down_revision: Union[str, Sequence[str], None] = '9c05c2079084'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('perfil', sa.Column('direccion', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('perfil', 'direccion')
    # ### end Alembic commands ###
