"""Creacion de tablas iniciales

Revision ID: 9c05c2079084
Revises: 
Create Date: 2026-02-17 15:39:29.851172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c05c2079084'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acceso',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ultimo_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acceso_id'), 'acceso', ['id'], unique=False)
    op.create_table('categoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categoria_id'), 'categoria', ['id'], unique=False)
    op.create_table('plataforma',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plataforma_id'), 'plataforma', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('password'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('perfil',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('pais', sa.String(), nullable=True),
    sa.Column('usuario_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_index(op.f('ix_perfil_id'), 'perfil', ['id'], unique=False)
    op.create_table('videojuego',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=True),
    sa.Column('descripcion', sa.String(), nullable=True),
    sa.Column('url_imagen', sa.String(), nullable=True),
    sa.Column('categoria_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categoria.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('categoria_id')
    )
    op.create_index(op.f('ix_videojuego_id'), 'videojuego', ['id'], unique=False)
    op.create_table('videojuego_plataforma',
    sa.Column('videojuego_id', sa.UUID(), nullable=False),
    sa.Column('plataforma_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['plataforma_id'], ['plataforma.id'], ),
    sa.ForeignKeyConstraint(['videojuego_id'], ['videojuego.id'], ),
    sa.PrimaryKeyConstraint('videojuego_id', 'plataforma_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('videojuego_plataforma')
    op.drop_index(op.f('ix_videojuego_id'), table_name='videojuego')
    op.drop_table('videojuego')
    op.drop_index(op.f('ix_perfil_id'), table_name='perfil')
    op.drop_table('perfil')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_plataforma_id'), table_name='plataforma')
    op.drop_table('plataforma')
    op.drop_index(op.f('ix_categoria_id'), table_name='categoria')
    op.drop_table('categoria')
    op.drop_index(op.f('ix_acceso_id'), table_name='acceso')
    op.drop_table('acceso')
    # ### end Alembic commands ###
